# Generated by Django 4.2.3 on 2023-08-26 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_email_alter_customuser_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='user',
        ),
    ]
