# Generated by Django 4.2.5 on 2023-09-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_customuser_fullname_alter_customuser_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phonenumber',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
